config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"

  resources :mailboxes do
    resources :inboxes, only: [:show]

    resources :tokens, only: [:create, :update]
    resources :mails, except: [:index, :destroy, :create, :new] do
      member do
        get 'download'
        get 'compose'
        post 'deliver'
      end
    end
  end

  resources :tokens, only: [:create, :update]

  get "/auth/:provider/callback" => 'tokens#create' # callback for authorization
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
    @mailboxes = Mailbox.includes(:tokens)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_information.html.erb
<div class="container">
  <div class="columns is-vcentered">
    <div class="column">
      <p class="title">
        POLYBOARD
      </p>
      <p class="subtitle">
        An email port for <strong>gmail</strong>
      </p>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<br />
<div class="container">
  <h1 class="title">Geting started</h1>
  <h2 class="subtitle">Quick Introduction</h2>
  <hr />
  <div class="hero-buttons">
    <%= link_to new_mailbox_path, class: "button is-info is-large" do %>
    <span class="icon is-medium"><i class="fa fa-laptop"></i></span> <span>Add <strong>Mailbox</strong></span>
    <% end %>

    <%= link_to mailboxes_path, class: "button is-dark is-large" do %>
    <span class="icon is-medium"><i class="fa fa-laptop"></i></span> <span>View <strong>Mailboxes</strong></span>
    <% end %>

    <p><strong>What are mailboxes?</strong> Mailboxes are simply categories. <strong>What can you do with a mailbox?</strong> Each mailbox can connect to multiple gmail accounts. In each account, all users can view emails.</p>
  </div>
  <br>
  <div>
    <h3 class="title is-4">This is how it looks like</h3>
    <div>
      <p>PolyBoard</p>
      <ul class="tree">
        <li>Mailbox
          <ul>
            <li>GMail Account
              <ul>
                <li>Emails</li>
              </ul>
            </li>
          </ul>
        </li>
        <li>Another Mailbox
          <ul>
            <li>Another GMail Account
              <ul>
                <li>Emails</li>
              </ul>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </div>

  <hr />
  <% unless @mailboxes.length.zero? %>
  <div>
    <h3 class="title is-4">This is all available records</h3>
    <p>PolyBoard</p>
    <ul class="tree">
    <% @mailboxes.each do |mailbox| %>
    <li><%= mailbox.name %>
      <% unless mailbox.tokens.length.zero? %>
      <ul>
        <% mailbox.tokens.each do |token| %>
        <li>
          <%= token.email %>
          <ul>
            <li><%= link_to "view emails", mailbox_mail_path(mailbox_id: mailbox.id, id: token.id) %></li>
            <li><%= link_to "create new email", compose_mailbox_mail_path(mailbox_id: mailbox.id, id: token.id) %></li>
          </ul>
        </li>
        <% end %>
      </ul>
      <% end %>
    </li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <br />
</div>