config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"

  resources :mailboxes do
    resources :inboxes, only: [:show]

    resources :tokens, only: [:create, :update]
    resources :mails, except: [:index, :destroy, :create, :new] do
      member do
        get 'download'
        get 'compose'
        post 'deliver'
      end
    end
  end

  resources :tokens, only: [:create, :update]

  get "/auth/:provider/callback" => 'tokens#create' # callback for authorization
end

app/models/mailbox.rb
class Mailbox < ApplicationRecord
  has_many :tokens
  belongs_to :created_by, class_name: 'User', foreign_key: :created_by_id

  has_attached_file :cover_photo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :cover_photo, content_type: /\Aimage\/.*\Z/

  validates :name, presence: true, uniqueness: true
end

app/controllers/mailboxes_controller.rb
class MailboxesController < ApplicationController
  before_action :authenticate_user!
  before_filter :find_mailbox, only: [:edit, :show, :update]
  before_filter :build_mailbox, only: [:new, :create]

  def index
    @mailboxes = Mailbox.all
  end
  
  def new
  end
  
  def create
    if @mailbox.valid?
      @mailbox.save!

      redirect_to @mailbox
    else
      render :new
    end
  end

  def show
  end
  
  def edit
  end
  
  def update
    @mailbox.name = mailbox_params[:name]
    @mailbox.description = mailbox_params[:description]
    @mailbox.cover_photo = mailbox_params[:cover_photo] unless mailbox_params[:cover_photo].blank?

    if @mailbox.valid?
      @mailbox.save!

      redirect_to @mailbox
    else
      render :edit
    end
  end
  
  private
  def mailbox_params
    params.require(:mailbox).permit(:name, :cover_photo, :description) rescue {}
  end
  
  def find_mailbox
    @mailbox = Mailbox.find(params[:id])
  end
  
  def build_mailbox
    @mailbox = Mailbox.new(mailbox_params.merge(created_by_id: current_user.id))
  end
end

app/helpers/mailboxes_helper.rb
module MailboxesHelper
  def is_mailbox_present?
    @mailbox.present? && @mailbox.persisted?
  end
end

app/views/mailboxes/_form.html.erb
<%= form_for(@mailbox) do |f| %>
<div class="control is-horizontal">
  <div class="control-label">
    <%= f.label :name, nil, class: 'label' %>
  </div>
  <div class="control is-grouped">
    <div class="control is-expanded">
      <%= f.text_field :name, class: 'input', placeholder: 'Name' %>
    </div>
  </div>
</div>

<div class="control is-horizontal">
  <div class="control-label">
    <%= f.label :cover_photo, nil, class: 'label' %>
  </div>
  <div class="control">
    <div class="control is-fullwidth">
      <%= f.file_field :cover_photo %>
      
      <% unless @mailbox.cover_photo.nil? %>
      <div class="control is-fullwidth is-text-right">
        <%= link_to "Uploaded Photo", @mailbox.cover_photo.url, target: '_blank' %>
      </div>
      <% end %>
    </div>
  </div>
</div>

<div class="control is-horizontal">
  <div class="control-label">
    <%= f.label :description, nil, class: 'label' %>
  </div>
  <div class="control">
    <%= f.text_area :description, class: 'textarea', placeholder: 'Description of the mailbox' %>
  </div>
</div>

<div class="has-text-centered">
  <%= f.submit "Save", class: 'button is-primary' %>
  <%= f.submit "Reset", type: "reset", class: 'button is-danger' %>
  <%= link_to "Cancel", mailboxes_path, class: "button" %>
</div>

<% end %>

app/views/mailboxes/_layout.html.erb
<div class="columns is-gapless is-full-height">
  <div class="column is-2 is-dark-gray">
    <%= render partial: "sidebar" %>
  </div>
  <div class="column padded-bottom-10">
    <%= yield %>
  </div>
</div>

app/views/mailboxes/_navigation.html.erb
<nav class="tabs is-boxed is-fullwidth">
  <div class="container">
    <ul>
      <li class="<%= tab_class(:index) %>">
        <%= link_to mailboxes_path do %>
        <i class="fa fa-bars fa-1" aria-hidden='true'></i>&nbsp;Mailboxes
        <% end %>
      </li>
      <li class="<%= tab_class(:new) %>">
        <%= link_to new_mailbox_path do %>
        <i class="fa fa-laptop fa-1" aria-hidden='true'></i>&nbsp;Add Mailbox
        <% end %>
      </li>
      <li class="<%= tab_class(:show) %>">
        <%= link_to (is_mailbox_present? ? mailbox_path(@mailbox.id) : '#'), class: "#{'is-disabled' unless is_mailbox_present?}" do %>
        <i class="fa fa-laptop fa-1" aria-hidden='true'></i>&nbsp;Show
        <% end %>
      </li>
      <li class="<%= tab_class(:edit) %>">
        <%= link_to (is_mailbox_present? ? edit_mailbox_path(@mailbox.id) : '#'), class: "#{'is-disabled' unless is_mailbox_present?}" do %>
        <i class="fa fa-laptop fa-1" aria-hidden='true'></i>&nbsp;Edit
        <% end %>
      </li>
    </ul>
  </div>
</nav>

app/views/mailboxes/_sidebar.html.erb
<aside class="menu padded">
  <p class="menu-label">
    Mailboxes
  </p>
  <ul class="menu-list">
    <% mailboxes.each do |mailbox| %>
    <li><%= link_to mailbox[0], mailbox_path(mailbox[1]), class: is_active_class(:id, mailbox[1].to_s) %></li>
    <% end %>
  </ul>
</aside>

app/views/mailboxes/_tabs.html.erb
<div class="tabs">
  <ul class="is-left">
    <li class="<%= tab_class(:index) %>">
      <%= link_to mailboxes_path do %>
      <i class="fa fa-bars fa-1" aria-hidden='true'></i>&nbsp;Mailboxes
      <% end %>
    </li>
    <li class="<%= tab_class(:new) %>">
      <%= link_to new_mailbox_path do %>
      <i class="fa fa-laptop fa-1" aria-hidden='true'></i>&nbsp;Add Mailbox
      <% end %>
    </li>
  </ul>
</div>

app/views/mailboxes/edit.html.erb
<div class="columns padded">
  <div class="column">
    <h1 class="title">Edit Mailbox</h1>
    <div class="column is-8 is-offset-2">
      <%= render partial: 'form' %>
    </div>
  </div>
</div>

app/views/mailboxes/index.html.erb
<div class="columns">
  <div class="column is-10 is-offset-1">
    <br/>
    <h1 class="title">Mailboxes</h1>
    
    <div class="columns is-half-quarter">
      <div class="column">
        <% @mailboxes.each do |mailbox| %>
        <div class="card is-fullwidth">
          <header class="card-header">
            <p class="card-header-title">
              <%= link_to mailbox_path(mailbox.id) do %>
              <i class="fa fa-file" aria-hidden></i>&nbsp;<%= mailbox.name %>
              <% end %>
            </p>
            <%= link_to edit_mailbox_path(mailbox.id), class: 'card-header-icon' do %>
            <i class="fa fa-edit" aria-hidden></i>&nbsp;
            <% end %>
          </header>
          <div class="card-content">
            <div class="content">
              <%= mailbox.description %>
            </div>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/mailboxes/new.html.erb
<div class="columns padded">
  <div class="column">
    <h1 class="title">Add New Mailbox</h1>
    <div class="column is-8 is-offset-2">
      <%= render partial: 'form' %>
    </div>
  </div>
</div>

app/views/mailboxes/show.html.erb
<div class="columns padded">
  <div class="column is-8 is-offset-2 ">
    <div class="card is-fullwidth">
      <header class="card-header">
        <h3 class="card-header-title"><%= @mailbox.name %></h3>
        <%= link_to edit_mailbox_path(@mailbox.id), class: "card-header-icon", title: "Edit Mailbox" do %>
        <i class="fa fa-edit"></i>
        <% end %>
      </header>
      <% unless notice.blank? %>
      <div class="card-content is-info">
        <p><%= notice %></p>
      </div>
      <% end %>
      <% unless @mailbox.cover_photo.blank? %>
      <div class="card-image">
        <figure class="image">
          <%= image_tag @mailbox.cover_photo.url %>
        </figure>
      </div>
      <% end %>
      <div class="card-content">
        <div class="content">
          <%= raw @mailbox.description.html_safe %>
          <br />
          <small>Date Created: <%= @mailbox.created_at %></small>
          <hr />
          <h5 class="subtitle">
            Emails Connected
            <%= link_to '/auth/google_oauth2', class: "is-pulled-right button", title: "Connect new email" do %>
            <i class="fa fa-google" aria-hidden="true"></i>&nbsp;Connect GMAIL Account
            <% end %>
          </h5>
          <% if @mailbox.tokens.count.zero? %>
          <p>No Emails are connected yet.</p>
          <% else %>
          <table class="table">
            <thead>
              <tr>
                <th>Email</th>
                <th>Added by</th>
                <th>Date Added</th>
                <th></th>
              </tr>
            </thead>
            <tfoot>
              <tr>
                <th>Email</th>
                <th>Added by</th>
                <th>Date Added</th>
                <th></th>
              </tr>
            </tfoot>
            <tbody>
              <% @mailbox.tokens.each do |token| %>
              <tr>
                <td><%= token.email %></td>
                <td><%= token.user.try(:username) %></td>
                <td class="is-icon"><%= token.created_at %></td>
                <td>
                  <%= link_to mailbox_mail_path(mailbox_id: @mailbox.id, id: token.id), class: "button" do %>
                  <i class="fa fa-envelope" aria-hidden="true"></i>&nbsp;View Emails
                  <% end %>
                </td>
              </tr>
              <% end %>
            </tbody>
          </table>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>